name: Build and Deploy 
on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  init_job:
    # this job will only run if the PR has been merged
    runs-on: ubuntu-latest
    steps:
      - run: |
          env
          echo REFS $GITHUB_SHA $GITHUB_REF 
          ls -la

      - name: Checkout  
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT

      - name: Dump Current SHA 
        env:
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
        run: echo $GITHUB_SHA

      - name: Upload all project files
        uses: actions/upload-artifact@v4
        with:
          name: all-project-files
          path: |
            .
            !node_modules/  # Исключаем node_modules, если они есть
            !.git/          # Исключаем .git директорию
          retention-days: 1  # Опционально: как долго хранить артефакт

      - name: Prepare email content  
        id: email  
        run: | 
          ls -la
          PR_TITLE="${{ github.event.pull_request.title }}"  
          PR_BODY="${{ github.event.pull_request.body }}"  
          PR_URL="${{ github.event.pull_request.html_url }}"  
            
          # Generate email HTML 
          EMAIL_HTML="<h2><strong>${PR_TITLE}</strong></h2>  
          <p>${PR_BODY}</p>  
          <p><a href=\"${PR_URL}\">PR Link</a></p>"  
            
          # Text version 
          EMAIL_TEXT="PR Title: ${PR_TITLE}  

          PR description:
          ${PR_BODY}

          PR Link: ${PR_URL}"  
            
          # Save to env
          echo "EMAIL_HTML<<EOF" >> $GITHUB_ENV  
          echo "$EMAIL_HTML" >> $GITHUB_ENV  
          echo "EOF" >> $GITHUB_ENV  
            
          echo "EMAIL_TEXT<<EOF" >> $GITHUB_ENV  
          echo "$EMAIL_TEXT" >> $GITHUB_ENV  
          echo "EOF" >> $GITHUB_ENV  
            
          echo "EMAIL_SUBJECT=New PR: ${PR_TITLE}" >> $GITHUB_ENV

      - name: Send Email
        uses: dawidd6/action-send-mail@6d98ae34d733f9a723a9e04e94f2f24ba05e1402 # v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{ env.EMAIL_SUBJECT }} 
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_EMAIL }}
          html_body: ${{ env.EMAIL_HTML }}